export type IconName =
  | "ic_svl_b1"
  | "ic_svl_b2"
  | "ic_svl_bs1"
  | "ic_svl_bs2"
  | "ic_svl_g1"
  | "ic_svl_g2"
  | "ic_svl_gs1"
  | "ic_svl_gs2"
  | "ic_svl_ib"
  | "ic_svl_ig"
  | "ic_svl_sib"
  | "ic_svl_sig"
  | "ic_maya"
  | "ic_pldt"
  | "ic_facebook"
  | "ic_tiktok"
  | "ic_instagram";
